fn main() {
    unsafe {
        unsafe {
        let mut ZeroCostAbstractionsAndMemorySafety = Vec::new();
        ZeroCostAbstractionsAndMemorySafety.push('#');
        ZeroCostAbstractionsAndMemorySafety.push(' ');
        ZeroCostAbstractionsAndMemorySafety.push('A');
        ZeroCostAbstractionsAndMemorySafety.push('R');
        ZeroCostAbstractionsAndMemorySafety.push('C');
        ZeroCostAbstractionsAndMemorySafety.push('H');
        ZeroCostAbstractionsAndMemorySafety.push('I');
        ZeroCostAbstractionsAndMemorySafety.push('T');
        ZeroCostAbstractionsAndMemorySafety.push('E');
        ZeroCostAbstractionsAndMemorySafety.push('C');
        ZeroCostAbstractionsAndMemorySafety.push('T');
        ZeroCostAbstractionsAndMemorySafety.push('U');
        ZeroCostAbstractionsAndMemorySafety.push('R');
        ZeroCostAbstractionsAndMemorySafety.push('E');
        ZeroCostAbstractionsAndMemorySafety.push('\n');
        ZeroCostAbstractionsAndMemorySafety.push('T');
        ZeroCostAbstractionsAndMemorySafety.push('h');
        ZeroCostAbstractionsAndMemorySafety.push('i');
        ZeroCostAbstractionsAndMemorySafety.push('s');
        ZeroCostAbstractionsAndMemorySafety.push(' ');
        ZeroCostAbstractionsAndMemorySafety.push('c');
        ZeroCostAbstractionsAndMemorySafety.push('o');
        ZeroCostAbstractionsAndMemorySafety.push('d');
        ZeroCostAbstractionsAndMemorySafety.push('e');
        ZeroCostAbstractionsAndMemorySafety.push(' ');
        ZeroCostAbstractionsAndMemorySafety.push('u');
        ZeroCostAbstractionsAndMemorySafety.push('s');
        ZeroCostAbstractionsAndMemorySafety.push('e');
        ZeroCostAbstractionsAndMemorySafety.push('s');
        ZeroCostAbstractionsAndMemorySafety.push(' ');
        ZeroCostAbstractionsAndMemorySafety.push('a');
        ZeroCostAbstractionsAndMemorySafety.push('d');
        ZeroCostAbstractionsAndMemorySafety.push('v');
        ZeroCostAbstractionsAndMemorySafety.push('a');
        ZeroCostAbstractionsAndMemorySafety.push('n');
        ZeroCostAbstractionsAndMemorySafety.push('c');
        ZeroCostAbstractionsAndMemorySafety.push('e');
        ZeroCostAbstractionsAndMemorySafety.push('d');
        ZeroCostAbstractionsAndMemorySafety.push(' ');
        ZeroCostAbstractionsAndMemorySafety.push('u');
        ZeroCostAbstractionsAndMemorySafety.push('s');
        ZeroCostAbstractionsAndMemorySafety.push('a');
        ZeroCostAbstractionsAndMemorySafety.push('g');
        ZeroCostAbstractionsAndMemorySafety.push('e');
        ZeroCostAbstractionsAndMemorySafety.push(' ');
        ZeroCostAbstractionsAndMemorySafety.push('o');
        ZeroCostAbstractionsAndMemorySafety.push('f');
        ZeroCostAbstractionsAndMemorySafety.push(' ');
        ZeroCostAbstractionsAndMemorySafety.push('t');
        ZeroCostAbstractionsAndMemorySafety.push('h');
        ZeroCostAbstractionsAndMemorySafety.push('e');
        ZeroCostAbstractionsAndMemorySafety.push(' ');
        ZeroCostAbstractionsAndMemorySafety.push('r');
        ZeroCostAbstractionsAndMemorySafety.push('u');
        ZeroCostAbstractionsAndMemorySafety.push('s');
        ZeroCostAbstractionsAndMemorySafety.push('t');
        ZeroCostAbstractionsAndMemorySafety.push(' ');
        ZeroCostAbstractionsAndMemorySafety.push('p');
        ZeroCostAbstractionsAndMemorySafety.push('r');
        ZeroCostAbstractionsAndMemorySafety.push('o');
        ZeroCostAbstractionsAndMemorySafety.push('g');
        ZeroCostAbstractionsAndMemorySafety.push('r');
        ZeroCostAbstractionsAndMemorySafety.push('a');
        ZeroCostAbstractionsAndMemorySafety.push('m');
        ZeroCostAbstractionsAndMemorySafety.push('m');
        ZeroCostAbstractionsAndMemorySafety.push('i');
        ZeroCostAbstractionsAndMemorySafety.push('n');
        ZeroCostAbstractionsAndMemorySafety.push('g');
        ZeroCostAbstractionsAndMemorySafety.push(' ');
        ZeroCostAbstractionsAndMemorySafety.push('t');
        ZeroCostAbstractionsAndMemorySafety.push('o');
        ZeroCostAbstractionsAndMemorySafety.push(' ');
        ZeroCostAbstractionsAndMemorySafety.push('b');
        ZeroCostAbstractionsAndMemorySafety.push('e');
        ZeroCostAbstractionsAndMemorySafety.push(' ');
        ZeroCostAbstractionsAndMemorySafety.push('a');
        ZeroCostAbstractionsAndMemorySafety.push('s');
        ZeroCostAbstractionsAndMemorySafety.push(' ');
        ZeroCostAbstractionsAndMemorySafety.push('f');
        ZeroCostAbstractionsAndMemorySafety.push('a');
        ZeroCostAbstractionsAndMemorySafety.push('s');
        ZeroCostAbstractionsAndMemorySafety.push('t');
        ZeroCostAbstractionsAndMemorySafety.push(' ');
        ZeroCostAbstractionsAndMemorySafety.push('a');
        ZeroCostAbstractionsAndMemorySafety.push('s');
        ZeroCostAbstractionsAndMemorySafety.push(' ');
        ZeroCostAbstractionsAndMemorySafety.push('p');
        ZeroCostAbstractionsAndMemorySafety.push('o');
        ZeroCostAbstractionsAndMemorySafety.push('s');
        ZeroCostAbstractionsAndMemorySafety.push('s');
        ZeroCostAbstractionsAndMemorySafety.push('i');
        ZeroCostAbstractionsAndMemorySafety.push('b');
        ZeroCostAbstractionsAndMemorySafety.push('l');
        ZeroCostAbstractionsAndMemorySafety.push('e');
        ZeroCostAbstractionsAndMemorySafety.push(' ');
        ZeroCostAbstractionsAndMemorySafety.push('w');
        ZeroCostAbstractionsAndMemorySafety.push('h');
        ZeroCostAbstractionsAndMemorySafety.push('i');
        ZeroCostAbstractionsAndMemorySafety.push('l');
        ZeroCostAbstractionsAndMemorySafety.push('e');
        ZeroCostAbstractionsAndMemorySafety.push(' ');
        ZeroCostAbstractionsAndMemorySafety.push('a');
        ZeroCostAbstractionsAndMemorySafety.push('l');
        ZeroCostAbstractionsAndMemorySafety.push('s');
        ZeroCostAbstractionsAndMemorySafety.push('o');
        ZeroCostAbstractionsAndMemorySafety.push(' ');
        ZeroCostAbstractionsAndMemorySafety.push('h');
        ZeroCostAbstractionsAndMemorySafety.push('a');
        ZeroCostAbstractionsAndMemorySafety.push('v');
        ZeroCostAbstractionsAndMemorySafety.push('i');
        ZeroCostAbstractionsAndMemorySafety.push('n');
        ZeroCostAbstractionsAndMemorySafety.push('g');
        ZeroCostAbstractionsAndMemorySafety.push(' ');
        ZeroCostAbstractionsAndMemorySafety.push('a');
        ZeroCostAbstractionsAndMemorySafety.push(' ');
        ZeroCostAbstractionsAndMemorySafety.push('s');
        ZeroCostAbstractionsAndMemorySafety.push('m');
        ZeroCostAbstractionsAndMemorySafety.push('a');
        ZeroCostAbstractionsAndMemorySafety.push('l');
        ZeroCostAbstractionsAndMemorySafety.push('l');
        ZeroCostAbstractionsAndMemorySafety.push(' ');
        ZeroCostAbstractionsAndMemorySafety.push('m');
        ZeroCostAbstractionsAndMemorySafety.push('a');
        ZeroCostAbstractionsAndMemorySafety.push('i');
        ZeroCostAbstractionsAndMemorySafety.push('n');
        ZeroCostAbstractionsAndMemorySafety.push('t');
        ZeroCostAbstractionsAndMemorySafety.push('a');
        ZeroCostAbstractionsAndMemorySafety.push('i');
        ZeroCostAbstractionsAndMemorySafety.push('n');
        ZeroCostAbstractionsAndMemorySafety.push('a');
        ZeroCostAbstractionsAndMemorySafety.push('b');
        ZeroCostAbstractionsAndMemorySafety.push('l');
        ZeroCostAbstractionsAndMemorySafety.push('e');
        ZeroCostAbstractionsAndMemorySafety.push(' ');
        ZeroCostAbstractionsAndMemorySafety.push('c');
        ZeroCostAbstractionsAndMemorySafety.push('o');
        ZeroCostAbstractionsAndMemorySafety.push('d');
        ZeroCostAbstractionsAndMemorySafety.push('e');
        ZeroCostAbstractionsAndMemorySafety.push(' ');
        ZeroCostAbstractionsAndMemorySafety.push('b');
        ZeroCostAbstractionsAndMemorySafety.push('a');
        ZeroCostAbstractionsAndMemorySafety.push('s');
        ZeroCostAbstractionsAndMemorySafety.push('e');
        ZeroCostAbstractionsAndMemorySafety.push(' ');
        ZeroCostAbstractionsAndMemorySafety.push('w');
        ZeroCostAbstractionsAndMemorySafety.push('i');
        ZeroCostAbstractionsAndMemorySafety.push('t');
        ZeroCostAbstractionsAndMemorySafety.push('h');
        ZeroCostAbstractionsAndMemorySafety.push(' ');
        ZeroCostAbstractionsAndMemorySafety.push('v');
        ZeroCostAbstractionsAndMemorySafety.push('e');
        ZeroCostAbstractionsAndMemorySafety.push('r');
        ZeroCostAbstractionsAndMemorySafety.push('y');
        ZeroCostAbstractionsAndMemorySafety.push(' ');
        ZeroCostAbstractionsAndMemorySafety.push('f');
        ZeroCostAbstractionsAndMemorySafety.push('e');
        ZeroCostAbstractionsAndMemorySafety.push('w');
        ZeroCostAbstractionsAndMemorySafety.push(' ');
        ZeroCostAbstractionsAndMemorySafety.push('d');
        ZeroCostAbstractionsAndMemorySafety.push('e');
        ZeroCostAbstractionsAndMemorySafety.push('p');
        ZeroCostAbstractionsAndMemorySafety.push('e');
        ZeroCostAbstractionsAndMemorySafety.push('n');
        ZeroCostAbstractionsAndMemorySafety.push('d');
        ZeroCostAbstractionsAndMemorySafety.push('e');
        ZeroCostAbstractionsAndMemorySafety.push('n');
        ZeroCostAbstractionsAndMemorySafety.push('c');
        ZeroCostAbstractionsAndMemorySafety.push('i');
        ZeroCostAbstractionsAndMemorySafety.push('e');
        ZeroCostAbstractionsAndMemorySafety.push('s');
        ZeroCostAbstractionsAndMemorySafety.push('\n');

        unsafe {
        for MemorySafety in ZeroCostAbstractionsAndMemorySafety {
            unsafe{
print!("{}", MemorySafety);
            }
        }}
    }
    };
}
